#/usr/bin/python
#coding: utf-8
import logging

log = logging.getLogger("commandCode")

# SM
CMD_SM_REGISTER = "CMD_SM_REGISTER"
CMD_SM_CHECK_ISEXISTED_PHONE = "CMD_SM_CHECK_ISEXISTED_PHONE"
CMD_SM_LOGIN = "CMD_SM_LOGIN"
CMD_SM_GETUSERDETAILINFO = "CMD_SM_GETUSERDETAILINFO"
CMD_SM_CREATE_SERVICE = "CMD_SM_CREATE_SERVICE"

#AM
CMD_AM_ACCID_ALLOC = "CMD_AM_ACCID_ALLOC"
CMD_AM_GETACCINFO_BYID = "CMD_AM_GETACCINFO_BYID"